[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
# Prefer IPv4 to avoid IPv6 EHOSTUNREACH in some hosts
NODE_OPTIONS = "--dns-result-order=ipv4first"
HOST = "0.0.0.0"
PRISMA_LOG_LEVEL = "info"
DATABASE_URL = "file:./prisma/dev.db"

[phases.setup]
# Use modern Node/npm compatible with Nuxt 4 & deps
nixPkgs = ["nodejs_22", "openssl"]
nixLibs = ["gcc-unwrapped"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "npx prisma migrate deploy || true; npx prisma db push; node .output/server/index.mjs"


